"""Bounded source bridge between CF4 distance groups and 2M++ groups.

The CF4 systemic redshift is not assumed to be generated by the CF4 distance
contributors or by the 2M++ group catalogue. This audit only measures which
observed associations and velocity equalities are available for a future
joint observation model. No field likelihood or candidate IC is evaluated.
"""

import csv
import hashlib
import json
import os
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
OUT = Path('/gpfs/kjhan/CF4/z0_density/r2_group_catalog_bridge_v1')
ELIGIBLE = Path('/gpfs/kjhan/CF4/z0_density/r2_inclusive_count_diagnostic_v1/row_diagnostics.npz')
SOURCES = {
    'cf4_groups.csv': 'bfdc0cfc0f172b48468e3a8fd05e87978c1ec68c341fb2d929fc1200f0123334',
    'cf4_galaxies.csv': '28e7b8bd386f53716ed84cddd67a6f7602f98bc1394923a312f906555da7f709',
    '2mpp_catalog.csv': '05d39f49af58caa7aa199420cc7354b3aa9fe3dbacf8d6c33222479c288fb23d',
    '2mpp_groups.csv': 'e83bcad0ebe97f6048f36b3235f66babaadf995fc2257302313160f35980057a',
    'cf4_2mpp_crossmatch_v1.csv': '64e4f8a1a8a612a19788ac759062930991a8ffe52bfa203635845fa1ad7a83bf',
}


def read_bound(name, digest):
    path = ROOT/'data'/name
    if hashlib.sha256(path.read_bytes()).hexdigest() != digest:
        raise ValueError(f'frozen source hash changed: {name}')
    with path.open(newline='', encoding='utf-8') as handle:
        return list(csv.DictReader(handle))


def summary(values):
    if not values:
        return None
    arr = np.asarray(values, dtype=np.float64)
    return dict(n=int(arr.size), median=float(np.median(arr)),
                p90=float(np.percentile(arr, 90)),
                p99=float(np.percentile(arr, 99)), maximum=float(np.max(arr)))


def main():
    if not os.environ.get('SLURM_JOB_ID'):
        raise RuntimeError('Slurm allocation required')
    if OUT.exists():
        raise FileExistsError(OUT)
    data = {name: read_bound(name, digest) for name, digest in SOURCES.items()}
    with np.load(ELIGIBLE, allow_pickle=False) as saved:
        eligible = set(map(int, saved['recno']))
    cf4_groups = {row['1PGC']: row for row in data['cf4_groups.csv']}
    twompp = {row['recno']: row for row in data['2mpp_catalog.csv']}
    twompp_groups = {row['GID']: row for row in data['2mpp_groups.csv']}
    if len(cf4_groups) != 38053 or len(twompp) != 72973 or len(twompp_groups) != 4002:
        raise ValueError('source cardinality changed')

    links = defaultdict(Counter)
    paired = 0
    ungrouped = 0
    orphan_gid = 0
    individual_vs_2mpp_group = []
    for row in data['cf4_2mpp_crossmatch_v1.csv']:
        if row['match_class'] != 'secure_joint_mark' or int(row['twompp_recno']) not in eligible:
            continue
        paired += 1
        galaxy = twompp[row['twompp_recno']]
        gid = galaxy['GID']
        if not gid:
            ungrouped += 1
            continue
        if gid not in twompp_groups:
            orphan_gid += 1
            continue
        if row['1PGC'] in cf4_groups:
            links[row['1PGC']][gid] += 1
            individual_vs_2mpp_group.append(abs(float(galaxy['Vcmb'])-
                                                  float(twompp_groups[gid]['Vcmb'])))

    distinct_gid = Counter()
    exact = []
    offset = []
    different = []
    secure_single = 0
    secure_multi = 0
    for pgc, gids in links.items():
        for gid in gids:
            distinct_gid[gid] += 1
        if len(gids) != 1:
            secure_multi += 1
            continue
        secure_single += 1
        gid = next(iter(gids))
        delta = abs(float(cf4_groups[pgc]['V3k'])-float(twompp_groups[gid]['Vcmb']))
        exact.append(delta)
        if delta <= 1:
            offset.append(delta)
        else:
            different.append(delta)

    # Distance-contributor rows are a different membership set from the
    # systemic-velocity source. Check only a naive weighted-modulus proposal,
    # so a failure cannot be mistaken for an identified CF4 recipe.
    distance_members = defaultdict(list)
    for row in data['cf4_galaxies.csv']:
        if row['DM'] and row['e_DM'] and float(row['e_DM']) > 0:
            distance_members[row['1PGC']].append((float(row['DM']), float(row['e_DM'])))
    dm_single = []
    dm_multi = []
    for pgc, group in cf4_groups.items():
        members = distance_members.get(pgc, ())
        if not members or not group['DMzp']:
            continue
        values = np.asarray(members)
        weight = values[:, 1]**-2
        proposal = float(np.dot(weight, values[:, 0])/np.sum(weight))
        target = dm_single if len(members) == 1 else dm_multi
        target.append(abs(float(group['DMzp'])-proposal))

    if paired != 14878 or orphan_gid > 3:
        raise ValueError('eligible secure/source group relation changed')
    result = dict(
        classification='R2_CF4_2MPP_GROUP_CATALOG_BRIDGE_SOURCE_ONLY',
        source_sha256=SOURCES,
        eligible_secure_matches=paired,
        secure_matches_without_2mpp_GID=ungrouped,
        secure_matches_with_missing_2mpp_group_row=orphan_gid,
        cf4_groups_with_at_least_one_mapped_2mpp_GID=len(links),
        cf4_groups_with_one_mapped_2mpp_GID=secure_single,
        cf4_groups_with_multiple_mapped_2mpp_GIDs=secure_multi,
        twompp_GIDs_linked_to_multiple_CF4_groups=sum(n > 1 for n in distinct_gid.values()),
        abs_CF4_V3k_minus_2mpp_group_Vcmb_km_s_one_GID=summary(exact),
        one_GID_delta_le_1_km_s=len(offset),
        one_GID_delta_gt_1_km_s=len(different),
        abs_2mpp_individual_minus_2mpp_group_Vcmb_km_s=summary(individual_vs_2mpp_group),
        abs_CF4_DMZP_minus_inverse_variance_individual_DM_mag=dict(
            singleton=summary(dm_single), multi_distance_contributor=summary(dm_multi)),
        limitation=('2M++ Lavaux-Hudson groups and CF4/Tully 2MASS groups are not '
                    'assumed identical. CF4 Ngal describes distance contributors, '
                    'not necessarily all systemic-velocity members. This is not a '
                    'survey mock, normalized likelihood, rate calibration or posterior.'),
    )
    OUT.mkdir(parents=True)
    (OUT/'result.json').write_text(json.dumps(result, indent=2, allow_nan=False)+'\n')
    print(json.dumps(result, allow_nan=False), flush=True)


if __name__ == '__main__':
    main()
