#!/usr/bin/env python3
"""Write a coherent 1LPT GRAFIC IC from the repaired z=0 density contrast."""
from __future__ import annotations
import argparse,os,json
from pathlib import Path
import numpy as np
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--out',type=Path,required=True); ap.add_argument('--astart',type=float,default=.02); a=ap.parse_args(); src=Path('/gpfs/kjhan/CF4/kf_design/low_high_splice_repair_bundle_v1/repaired_field.npz'); field=np.asarray(np.load(src,allow_pickle=False)['field'],float); N=field.shape[0]; Lh=384.; h=.746; Om=.31; Ol=1-Om; H0=100*h; aa=a.astart; f=Om**.55; H=H0*np.sqrt(Om/aa**3+Ol); delta=(aa*field).astype(np.float32); fk=np.fft.fftn(delta.astype(float)); kh=2*np.pi*np.fft.fftfreq(N,d=Lh/N); kx,ky,kz=np.meshgrid(kh,kh,kh,indexing='ij'); kp=np.sqrt(kx*kx+ky*ky+kz*kz)*h; vxk=np.zeros_like(fk,dtype=complex); vyk=np.zeros_like(fk,dtype=complex); vzk=np.zeros_like(fk,dtype=complex); nz=kp>0; fac=1j*aa*H*f; vxk[nz]=fac*fk[nz]*(kx[nz]*h)/(kp[nz]**2); vyk[nz]=fac*fk[nz]*(ky[nz]*h)/(kp[nz]**2); vzk[nz]=fac*fk[nz]*(kz[nz]*h)/(kp[nz]**2); vx=np.fft.ifftn(vxk).real; vy=np.fft.ifftn(vyk).real; vz=np.fft.ifftn(vzk).real; os.environ['PYTHONPATH']=str(Path(__file__).resolve().parents[1]/'src')+':'+os.environ.get('PYTHONPATH',''); from grafic_io import write_grafic_ic,read_grafic_field; a.out.mkdir(parents=True,exist_ok=True); info=write_grafic_ic(str(a.out),delta,vx,vy,vz,L_mpc_h=Lh,h=h,astart=aa,omega_m=Om,omega_l=Ol,offset_mpc=(0.,0.,0.)); d2,meta=read_grafic_field(str(a.out/'ic_deltab')); result={'schema':'ouruniv-cf4-density-to-grafic-ic-v1','source':str(src),'output':str(a.out),'N':N,'box_cMpc_h':Lh,'cell_cMpc_h':Lh/N,'astart':aa,'cosmology':{'h':h,'Omega_m':Om},'delta_ic_std':float(delta.std()),'velocity_rms_km_s':[float(vx.std()),float(vy.std()),float(vz.std())],'roundtrip_max_abs_error':float(np.max(np.abs(d2-delta))),'grafic':info,'production_evolution_started':False}; (a.out/'ic_provenance.json').write_text(json.dumps(result,indent=2,sort_keys=True)+'\n'); print(json.dumps(result,sort_keys=True))
if __name__=='__main__': main()
