#!/usr/bin/env python3
"""Score and gate the fresh V8 Local-Group importance-sampling bank."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import numpy as np

from cf4_lg_midpoint_proposal import diagonal_normal_logpdf, mixture_logpdf
from cf4_lg_z0_likelihood import logmeanexp, logsumexp, score_catalog, sha256_file


def pair_key(pair: dict[str, Any]) -> tuple[int, int]:
    return tuple(sorted((int(pair["halo_i"]), int(pair["halo_j"]))))


def load_program(path: Path) -> dict[str, Any]:
    program = json.loads(path.read_text())
    if program.get("status") != "frozen_authorized_before_fresh_v8_generation":
        raise RuntimeError("V8 program is not prospectively frozen")
    repo = Path(__file__).resolve().parents[1]
    authorization = program["authorization"]
    record_path = repo / authorization["result_record_path"]
    if sha256_file(record_path) != authorization["result_record_sha256"]:
        raise RuntimeError("V8 proposal-audit result record hash mismatch")
    record = json.loads(record_path.read_text())
    if record.get("status") != authorization["required_status"]:
        raise RuntimeError("V8 proposal audit did not authorize fresh generation")
    if int(program["seed_bank"]["count"]) != int(
        record["decision"]["authorized_bank_size"]
    ):
        raise RuntimeError("V8 bank size differs from the audited authorization")
    return program


def _manifest_importance(
    entry: dict[str, Any], program: dict[str, Any]
) -> dict[str, float]:
    value = np.asarray(
        entry["protohalo_midpoint_offset_draw_mpc_h"], dtype=np.float64
    )
    peak = program["peak_constraints"]
    prior = peak["protohalo_midpoint_prior"]
    components = peak["protohalo_midpoint_sampling_proposal"]["components"]
    log_prior = diagonal_normal_logpdf(value, prior)
    log_proposal = mixture_logpdf(value, components)
    stored = entry["protohalo_midpoint_source"]
    comparisons = {
        "log_target_prior": log_prior,
        "log_sampling_proposal": log_proposal,
        "log_target_prior_over_sampling_proposal": log_prior - log_proposal,
    }
    for key, expected in comparisons.items():
        if not np.isclose(float(stored[key]), expected, rtol=0.0, atol=1.0e-12):
            raise RuntimeError(
                f"proposal manifest has an inconsistent importance term: {key}"
            )
    return comparisons


def _preview_pair(pair: dict[str, Any]) -> dict[str, Any]:
    result = dict(pair)
    result["m1_fof_msun_h"] = float(pair["masses_msun_h"][0])
    result["m2_fof_msun_h"] = float(pair["masses_msun_h"][1])
    # Existing recentered-P1 code sorts ascending on this diagnostic field.
    result["ranking_score"] = -float(pair["log_likelihood"])
    return result


def score_fresh_bank(
    program_path: Path,
    manifest_path: Path,
    p2_path: Path,
    output_path: Path,
    pair_output_path: Path,
) -> dict[str, Any]:
    program = load_program(program_path)
    manifest = json.loads(manifest_path.read_text())
    if manifest.get("status") != "complete":
        raise RuntimeError("V8 proposal manifest is incomplete")
    if manifest.get("config_sha256") != sha256_file(program_path):
        raise RuntimeError("V8 proposal manifest was not generated by this program")
    entries = {int(row["proposal_seed"]): row for row in manifest["entries"]}
    if len(entries) != int(program["seed_bank"]["count"]):
        raise RuntimeError("V8 proposal manifest has the wrong bank size")

    p2 = json.loads(p2_path.read_text())
    if p2.get("status") != "complete":
        raise RuntimeError("V8 P2 screen is incomplete")
    p2_directory = p2_path.parent
    rows = []
    pair_rows = []
    for p2_row in p2["results"]:
        parent_seed = int(p2_row["parent_seed"])
        seed = int(p2_row["small_scale_seed"])
        if seed not in entries:
            raise RuntimeError(f"P2 seed {seed} is absent from the proposal manifest")
        catalog_path = p2_directory / f"halos_p{parent_seed}_s{seed}.npz"
        with np.load(catalog_path, allow_pickle=False) as data:
            box_size = float(data["box_size"])
            catalog = score_catalog(
                data["halo_pos"], data["halo_vel"], data["halo_mass"],
                centre=np.full(3, box_size / 2.0),
                box_size=box_size,
                program=program,
            )
        importance = _manifest_importance(entries[seed], program)
        rows.append({
            "parent_seed": parent_seed,
            "small_scale_seed": seed,
            "catalog": str(catalog_path.resolve()),
            "catalog_sha256": sha256_file(catalog_path),
            "passed_parent_centered_P1": True,
            "passed_hard_P2_at_realization_level": bool(p2_row["screen_pass"]),
            "midpoint_importance": importance,
            **catalog,
        })
        candidates = [_preview_pair(pair) for pair in catalog["candidate_pairs"]]
        pair_rows.append({
            "parent_seed": parent_seed,
            "small_scale_seed": seed,
            "n_screen_pairs": len(candidates),
            "screen_pass": bool(candidates),
            "best_pair": candidates[0] if candidates else None,
            "screen_pairs": candidates,
        })

    report = {
        "schema": "ouruniv-lg-z0-forward-importance-v8-score-result-v1",
        "status": "complete",
        "program": str(program_path.resolve()),
        "program_sha256": sha256_file(program_path),
        "proposal_manifest": str(manifest_path.resolve()),
        "proposal_manifest_sha256": sha256_file(manifest_path),
        "p2_result": str(p2_path.resolve()),
        "p2_result_sha256": sha256_file(p2_path),
        "generated_bank_size": len(entries),
        "parent_P1_survivor_catalogs": len(rows),
        "finite_likelihood_catalogs": int(sum(
            np.isfinite(row["log_likelihood"]) for row in rows
        )),
        "rows": rows,
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    pair_report = {
        "schema": "ouruniv-lg-z0-forward-importance-v8-recenter-input-v1",
        "status": "complete",
        "source_likelihood_result": str(output_path.resolve()),
        "source_likelihood_result_sha256": sha256_file(output_path),
        "source_p2_result": str(p2_path.resolve()),
        "source_p2_result_sha256": sha256_file(p2_path),
        "results": pair_rows,
        "passing_combinations": [
            [row["parent_seed"], row["small_scale_seed"]]
            for row in pair_rows if row["screen_pass"]
        ],
    }
    pair_output_path.write_text(
        json.dumps(pair_report, indent=2, sort_keys=True) + "\n"
    )
    return report


def evaluate_importance_gate(
    likelihood: dict[str, Any],
    preview: dict[str, Any],
    hard_p2: dict[str, Any],
    selection: dict[str, Any],
) -> dict[str, Any]:
    """Intersect pair identity across likelihood, P1, and hard P2 and weight."""
    preview_by_seed = {
        int(row["small_scale_seed"]): row for row in preview["rows"]
    }
    hard_by_seed = {
        int(row["small_scale_seed"]): row for row in hard_p2["results"]
    }
    rows = []
    log_weights = []
    for source in likelihood["rows"]:
        seed = int(source["small_scale_seed"])
        hard_keys = {
            pair_key(pair) for pair in hard_by_seed[seed].get("screen_pairs", [])
        }
        preview_keys = {
            pair_key(row["screen_pair"])
            for row in preview_by_seed.get(seed, {}).get("pair_rows", [])
            if row["preview_pass"]
        }
        eligible_keys = hard_keys & preview_keys
        eligible_pairs = [
            pair for pair in source["candidate_pairs"]
            if pair_key(pair) in eligible_keys
        ]
        pair_log_likelihood = logmeanexp(np.asarray([
            pair["log_likelihood"] for pair in eligible_pairs
        ], dtype=np.float64))
        correction = float(source["midpoint_importance"][
            "log_target_prior_over_sampling_proposal"
        ])
        log_weight = pair_log_likelihood + correction
        log_weights.append(log_weight)
        eligible_pairs.sort(key=lambda row: row["log_likelihood"], reverse=True)
        rows.append({
            "parent_seed": int(source["parent_seed"]),
            "small_scale_seed": seed,
            "n_hard_P2_pairs": len(hard_keys),
            "n_recentered_P1_pairs": len(preview_keys),
            "n_jointly_eligible_pairs": len(eligible_pairs),
            "eligible_pair_logmean_likelihood": pair_log_likelihood,
            "log_midpoint_importance_correction": correction,
            "unnormalized_log_importance_weight": log_weight,
            "best_eligible_pair": eligible_pairs[0] if eligible_pairs else None,
        })

    log_weights_array = np.asarray(log_weights, dtype=np.float64)
    finite = np.isfinite(log_weights_array)
    weights = np.zeros(len(rows), dtype=np.float64)
    if np.any(finite):
        weights[finite] = np.exp(
            log_weights_array[finite] - logsumexp(log_weights_array[finite])
        )
    for row, weight in zip(rows, weights):
        row["normalized_importance_weight"] = float(weight)
    ess = float(1.0 / np.sum(weights**2)) if np.any(weights) else 0.0
    maximum = float(weights.max(initial=0.0))
    checks = {
        "minimum_jointly_eligible_realizations": (
            int(np.count_nonzero(finite))
            >= int(selection["minimum_jointly_eligible_realizations"])
        ),
        "minimum_fresh_importance_ESS": (
            ess >= float(selection["minimum_fresh_importance_ESS"])
        ),
        "maximum_fresh_single_weight": (
            maximum <= float(selection["maximum_fresh_single_weight"])
        ),
    }
    ranked = sorted(
        rows, key=lambda row: row["normalized_importance_weight"], reverse=True
    )
    return {
        "n_catalogs": len(rows),
        "n_jointly_eligible_realizations": int(np.count_nonzero(finite)),
        "effective_sample_size": ess,
        "maximum_single_normalized_weight": maximum,
        "checks": checks,
        "passed": all(checks.values()),
        "selected_candidate": ranked[0] if np.any(finite) else None,
        "rows": rows,
    }


def gate_fresh_bank(
    program_path: Path,
    likelihood_path: Path,
    preview_path: Path,
    p2_path: Path,
    output_path: Path,
) -> dict[str, Any]:
    program = load_program(program_path)
    likelihood = json.loads(likelihood_path.read_text())
    preview = json.loads(preview_path.read_text())
    hard_p2 = json.loads(p2_path.read_text())
    if likelihood.get("program_sha256") != sha256_file(program_path):
        raise RuntimeError("likelihood result does not belong to this V8 program")
    if likelihood.get("p2_result_sha256") != sha256_file(p2_path):
        raise RuntimeError("likelihood and hard-P2 inputs differ")
    expected_pair_hash = preview.get("p2_result_sha256")
    pair_input = Path(preview["p2_result"])
    if expected_pair_hash != sha256_file(pair_input):
        raise RuntimeError("recentered-P1 pair input hash mismatch")
    pair_report = json.loads(pair_input.read_text())
    if pair_report.get("source_likelihood_result_sha256") != sha256_file(
        likelihood_path
    ):
        raise RuntimeError("recentered-P1 pairs and likelihood result differ")
    if pair_report.get("source_p2_result_sha256") != sha256_file(p2_path):
        raise RuntimeError("recentered-P1 pairs and hard-P2 result differ")

    gate = evaluate_importance_gate(
        likelihood, preview, hard_p2, program["selection_policy"]
    )
    report = {
        "schema": "ouruniv-lg-z0-forward-importance-v8-gate-result-v1",
        "status": (
            "complete_pass_waiting_RAMSSES_review"
            if gate["passed"] else "complete_fail_v8_closed"
        ),
        "program": str(program_path.resolve()),
        "program_sha256": sha256_file(program_path),
        "likelihood_result": str(likelihood_path.resolve()),
        "likelihood_result_sha256": sha256_file(likelihood_path),
        "recentered_P1_result": str(preview_path.resolve()),
        "recentered_P1_result_sha256": sha256_file(preview_path),
        "hard_P2_result": str(p2_path.resolve()),
        "hard_P2_result_sha256": sha256_file(p2_path),
        "RAMSES_launched": False,
        **gate,
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    return report


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    score_parser = subparsers.add_parser("score")
    score_parser.add_argument("--program", type=Path, required=True)
    score_parser.add_argument("--proposal-manifest", type=Path, required=True)
    score_parser.add_argument("--p2-result", type=Path, required=True)
    score_parser.add_argument("--out", type=Path, required=True)
    score_parser.add_argument("--pair-out", type=Path, required=True)
    gate_parser = subparsers.add_parser("gate")
    gate_parser.add_argument("--program", type=Path, required=True)
    gate_parser.add_argument("--likelihood-result", type=Path, required=True)
    gate_parser.add_argument("--recentered-p1-result", type=Path, required=True)
    gate_parser.add_argument("--p2-result", type=Path, required=True)
    gate_parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    if args.command == "score":
        report = score_fresh_bank(
            args.program, args.proposal_manifest, args.p2_result,
            args.out, args.pair_out,
        )
        summary = {
            key: report[key] for key in (
                "status", "generated_bank_size", "parent_P1_survivor_catalogs",
                "finite_likelihood_catalogs",
            )
        }
    else:
        report = gate_fresh_bank(
            args.program, args.likelihood_result, args.recentered_p1_result,
            args.p2_result, args.out,
        )
        summary = {
            key: report[key] for key in (
                "status", "n_catalogs", "n_jointly_eligible_realizations",
                "effective_sample_size", "maximum_single_normalized_weight",
                "checks", "RAMSES_launched",
            )
        }
    print(json.dumps(summary, indent=2), flush=True)


if __name__ == "__main__":
    main()
